# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

macros:
    'llama-server': >
        /usr/bin/llama-server
        --port ${PORT}

healthCheckTimeout: 30

models:
    gemma-4-E4B-it:
        name: 'Gemma 4 E4B'
        ttl: 30
        cmd: |
            ${llama-server}
            --hf-repo unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL
            --n-gpu-layers 999
            --flash-attn on
            --parallel 1
            --ctx-size 32000
            --cache-ram 0
            --ubatch-size 2048
            --batch-size 2048
    zeta-2:
        name: 'Zeta 2'
        ttl: 1800
        cmd: |
            ${llama-server}
            --hf-repo bartowski/zed-industries_zeta-2-GGUF:Q4_K_M
            --n-gpu-layers 999
            --flash-attn on
            --parallel 1
            --ctx-size 8000
