# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

macros:
    'llama-server': >
        /app/llama-server
        --port ${PORT}

healthCheckTimeout: 30

models:
    llama-3.1-8b-instruct:
        name: 'Llama 3.1 8b Instruct'
        ttl: 30
        cmd: |
            /usr/bin/llama-server
            --port ${PORT}
            --hf-repo unsloth/Llama-3.1-8B-Instruct-GGUF:Q5_K_M
            --jinja
            --n-gpu-layers 999
            --flash-attn on
            --ctx-size 0
            --ubatch-size 2048
            --batch-size 2048
