# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

macros:
    'llama-server': >
        /usr/bin/llama-server
        --port ${PORT}

healthCheckTimeout: 30

models:
    llama-3.1-8b-instruct:
        name: 'Llama 3.1 8b Instruct'
        ttl: 30
        cmd: |
            ${llama-server}
            --hf-repo unsloth/Llama-3.1-8B-Instruct-GGUF:Q5_K_M
            --jinja
            --n-gpu-layers 999
            --flash-attn on
            --parallel 1
            --ctx-size 32000
            --ubatch-size 2048
            --batch-size 2048
            --cache-ram 0
    zeta-2:
        name: 'Zeta 2'
        ttl: 1800
        cmd: |
            ${llama-server}
            --hf-repo bartowski/zed-industries_zeta-2-GGUF:Q4_K_M
            --n-gpu-layers 999
            --flash-attn on
            --parallel 1
            --ctx-size 8000
